### ISSUE TITLE
inbox label issue :

### ISSUE THREAD

**Issue by rohitkalampatil** [rohitkalampatil/LeaveApp#2]
When clicked to update student from hod pannel on update page inbox label changing

**Comment by RohitKalam** [comment]
String branch = (String) session.getAttribute("branch");

                int c = 0;

                Statement st = null;
                Connection c1 = null;
                String q = "";
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    c1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "root");
                    st = c1.createStatement();
//use following query                    
q = "select count(applicationid) from leaveapplications where status='pending' and branch='" + branch + "'";
                    ResultSet r = st.executeQuery(q);
                    r.next();
                    c = r.getInt("count(applicationid)");

                } catch (Exception e) {
                    out.print(e);
                }


and change 
String  branch="" to String  stdbranch = "";

**Comment by RohitKalam** [comment]
`String branch = (String) session.getAttribute("branch");

            int c = 0;

            Statement st = null;
            Connection c1 = null;
            String q = "";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                c1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "root");
                st = c1.createStatement();
//use following query
q = "select count(applicationid) from leaveapplications where status='pending' and branch='" + branch + "'";
ResultSet r = st.executeQuery(q);
r.next();
c = r.getInt("count(applicationid)");

            } catch (Exception e) {
                out.print(e);
            }`

**Comment by RohitKalam** [comment]
`
           String branch = (String) session.getAttribute("branch");

            int c = 0;

            Statement st = null;
            Connection c1 = null;
            String q = "";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                c1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "root");
                st = c1.createStatement();
                //use following query
                q = "select count(applicationid) from leaveapplications where status='pending' and branch='" + branch + "'";
                ResultSet r = st.executeQuery(q);
                r.next();
                c = r.getInt("count(applicationid)");

            } catch (Exception e) {
                out.print(e);
            }
           //and change
           String branch="" to String stdbranch = "";`
